name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送符合 v*.*.* 格式的新标签时触发

permissions:
  contents: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            goarm: ''
          - goos: linux
            goarch: amd64
            goarm: ''
          - goos: darwin
            goarch: arm64
            goarm: ''
          - linux_configs: mips
          # 其他架构同样可以定义
      fail-fast: false

    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          mkdir -p build_assets
          OUTPUT="build_assets/EasierConnect"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          go build -v -o "$OUTPUT" -trimpath -ldflags "-s -w -buildid=" .

      - name: Create ZIP
        run: |
          cd build_assets
          ZIP_NAME="EasierConnect-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goarm }}" != "" ]; then
            ZIP_NAME="${ZIP_NAME}-${{ matrix.goarm }}"
          fi
          ZIP_NAME="${ZIP_NAME}.zip"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            zip -j "$ZIP_NAME" "EasierConnect.exe"
          else
            zip -j "$ZIP_NAME" "EasierConnect"
          fi
          mv "$ZIP_NAME" ..

      - name: Publish Release for each build
        run: |
          TAG_NAME=${{ github.ref_name }}
          gh release create "$TAG_NAME" build_assets/*.zip \
            --title "$TAG_NAME" \
            --notes "Release $TAG_NAME" || echo "Release already exists. Adding files."
          gh release upload "$TAG_NAME" build_assets/*.zip --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
