name: Release

on:
  release:
    types: [prereleased]
  push:
    branches:
      - home
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/*.yml"

permissions: write-all

jobs:
  build:
    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [ "amd64", "386" ]
        exclude:
          - goarch: 386
            goos: darwin
        include:
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 5
          - goos: windows
            goarch: arm
            goarm: 7
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: riscv64
          - goos: windows
            goarch: arm64
          - goos: android
            goarch: arm64
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips
      fail-fast: false

    runs-on: ubuntu-latest
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ^1.19

      - name: Get project dependencies
        run: go mod download

      - name: Build
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/EasierConnect -trimpath -ldflags "-s -w -buildid=" .

      - name: Rename Windows EasierConnect
        if: matrix.goos == 'windows'
        run: |
          cd ./build_assets || exit 1
          mv EasierConnect EasierConnect.exe

      - name: Create ZIP archive
        run: |
          pushd build_assets || exit 1
          zip -9vr ../EasierConnect-$GOOS-$GOARCH$GOARM.zip .
          popd || exit 1

      - name: Upload release binary
        if: github.event_name == 'release'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          gh release upload ${{ github.event.release.tag_name }} EasierConnect-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm }}.zip
