name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  build_and_release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [windows, linux, darwin, android]
        goarch: ["amd64", "386", "arm", "arm64", "riscv64", "mips64", "mips64le", "mipsle", "mips"]
        include:
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm
            goarm: 6
          - goos: linux
            goarch: arm
            goarm: 5
          - goos: windows
            goarch: arm
            goarm: 7
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: riscv64
          - goos: windows
            goarch: arm64
          - goos: android
            goarch: arm64
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips
      fail-fast: false

    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      CGO_ENABLED: 0

    steps:
      - name: Checkout codebase
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "^1.22"

      - name: Show build info
        id: get_filename
        run: |
          export _NAME=$GOOS-$GOARCH${GOARM:-}
          echo "GOOS: $GOOS, GOARCH: $GOARCH, GOARM: ${GOARM:-N/A}, ASSET_NAME: $_NAME"
          echo "ASSET_NAME=$_NAME" >> $GITHUB_ENV

      - name: Get dependencies
        run: go mod download

      - name: Build binary
        run: |
          mkdir -p build_assets
          go build -v -o build_assets/EasierConnect -trimpath -ldflags "-s -w -buildid=" .

      - name: Rename Windows Binary
        if: matrix.goos == 'windows'
        run: |
          cd build_assets
          mv EasierConnect EasierConnect.exe

      - name: Create ZIP archive
        run: |
          pushd build_assets
          zip -9vr ../EasierConnect-$ASSET_NAME.zip *
          popd

      # 使用softprops/action-gh-release直接创建或更新Release并上传产物
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          tag_name: ${{ github.ref_name }}
          name: "Release ${{ github.ref_name }}"
          body: "Automated release of ${{ github.ref_name }}"
          draft: false
          prerelease: false
          files: "./EasierConnect-${{ env.ASSET_NAME }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
