name: Release

on:
  push:
    tags:
      - 'v*.*.*'  # 仅在推送符合 v*.*.* 格式的新标签时触发

permissions:
  contents: write
  actions: write
  # 根据需要添加其他权限

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            goarm: ''
          - goos: windows
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: amd64
            goarm: ''
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: darwin
            goarch: arm64
            goarm: ''
          - goos: linux
            goarch: arm64
            goarm: ''
          - goos: linux
            goarch: riscv64
            goarm: ''
          - goos: windows
            goarch: arm64
            goarm: ''
          - goos: android
            goarch: arm64
            goarm: ''
          - goos: linux
            goarch: mips64
            goarm: ''
          - goos: linux
            goarch: mips64le
            goarm: ''
          - goos: linux
            goarch: mipsle
            goarm: ''
          - goos: linux
            goarch: mips
            goarm: ''
      fail-fast: false

    env:
      CGO_ENABLED: 0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.22'

      - name: Get dependencies
        run: go mod download

      - name: Build
        run: |
          mkdir -p build_assets
          OUTPUT="build_assets/EasierConnect"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            OUTPUT="${OUTPUT}.exe"
          fi
          go build -v -o "$OUTPUT" -trimpath -ldflags "-s -w -buildid=" .

      - name: Create ZIP
        run: |
          cd build_assets
          ZIP_NAME="EasierConnect-${{ matrix.goos }}-${{ matrix.goarch }}"
          if [ "${{ matrix.goarm }}" != "" ]; then
            ZIP_NAME="${ZIP_NAME}-${{ matrix.goarm }}"
          fi
          ZIP_NAME="${ZIP_NAME}.zip"
          if [ "${{ matrix.goos }}" == "windows" ]; then
            zip -j "$ZIP_NAME" "EasierConnect.exe"
          else
            zip -j "$ZIP_NAME" "EasierConnect"
          fi
          mv "$ZIP_NAME" ..

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: >-
            EasierConnect-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm != '' && format('-%s', matrix.goarm) || '' }}
          path: >-
            EasierConnect-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.goarm != '' && format('-%s', matrix.goarm) || '' }}.zip
  

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: build_assets

      - name: Verify downloaded artifacts
        run: |
          echo "List of downloaded artifacts:"
          ls -lhR build_assets

      - name: Create Release and Upload Assets
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: build_assets/**/*.zip
          draft: false
          prerelease: false

