name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin, windows]
        goarch: ["amd64", "386", "arm64"]
        exclude:
          - goos: darwin
            goarch: 386
          - goos: windows
            goarch: 386
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Get version from tag
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/} | cut -d'v' -f2)" >> $GITHUB_ENV
      - name: Build
        run: |
          mkdir -p release
          go mod tidy
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o release/homeai_${{ matrix.goos }}_${{ matrix.goarch }}_v${{ env.VERSION }}
      - name: Upload release archive
        uses: actions/upload-artifact@v4
        with:
          name: release-latest
          path: ./release

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download release archive
        uses: actions/download-artifact@v4
        with:
          name: release-latest
          path: ./release
      - name: Get version from tag
        run: echo "VERSION=$(echo ${GITHUB_REF#refs/tags/} | cut -d'v' -f2)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release v${{ env.VERSION }}
          draft: false
          prerelease: false
      - name: Upload Release Archive
        run: |
          for file in ./release/*; do
            echo "Uploading $file..."
            gh release upload ${{ github.ref }} "$file" --clobber
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
